title: Fernando Feitosa
logo: /assets/logo.png
description: Ph.D. Candidate <br/> Department of Political Science <br/> University of Montreal <br/> <li><a href="mailto:hankquinlanhub@gmail.com">email</a></li>
show_downloads: false
theme: jekyll-theme-minimal
