title: Fernando Feitosa
logo: /assets/logo.png
description: <p align="center">  Ph.D. Candidate <br/> Department of Political Science <br/> University of Montreal </p>
show_downloads: false
theme: jekyll-theme-minimal
