title: Fernando Feitosa
logo: /assets/logo.png
description: Ph.D. Candidate <br/> Department of Political Science <br/> University of Montreal <br/> <a href="https://www.chairedemocratie.com/">Publications</a> <a href="https://www.chairedemocratie.com/">Datasets</a> <ul> <li><a href="mailto:f.feitosa.ribeiro@umontreal.ca">E-mail</a></li> <li><a href="https://twitter.com/frfeitosa">Twitter</a></li> <li><a href="https://twitter.com/frfeitosa">Twitter</a></li>
show_downloads: false
theme: jekyll-theme-minimal
