title: Fernando Feitosa
logo: /assets/logo.png
description: Ph.D. Candidate <br/> Department of Political Science <br/> University of Montreal <br/> <ul> <li><a href="mailto:f.feitosa.ribeiro@umontreal.ca">E-mail</a></li> </ul>
show_downloads: false
theme: jekyll-theme-minimal
