title: Fernando Feitosa
logo: /assets/logo.png
description: Ph.D. Candidate <br/> Department of Political Science <br/> University of Montreal <br/> <ul> <li><a href="mailto:f.feitosa.ribeiro@umontreal.ca">E-mail</a></li> <li><a href="https://twitter.com/frfeitosa">Twitter</a></li> </ul> <nav><ul><li><a href="/">Home</a></li> <li><a href="/publications">Publications</a></li><li><a href="/datasets">Datasets</a></li></ul></nav>
show_downloads: false
theme: jekyll-theme-minimal
